# Generated by Django 2.2.12 on 2022-04-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Порядок отображения')),
                ('picture', models.FileField(blank=True, default='', null=True, upload_to='', verbose_name='Картинка/фото')),
                ('title', models.TextField(blank=True, default='', null=True, verbose_name='Заголовок (элемента)')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='Основной текст')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadescr', models.TextField(blank=True, default='', null=True, verbose_name='Meta Description')),
                ('metakeywords', models.TextField(blank=True, default='', null=True, verbose_name='Meta Keyword')),
                ('title', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Заголовок вкладки')),
                ('phone', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='ТЕлефон для всех мест на сайте')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email для рассылки заявок')),
                ('date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата и время проведения')),
                ('registry', models.BooleanField(default=False, verbose_name='Реестр месяца отправлен')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(blank=True, default=0, null=True, unique=True, verbose_name='Порядок отображения')),
                ('title', models.TextField(blank=True, default='', null=True, verbose_name='Заголовок (блока)')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='Основной текст')),
                ('picture', models.FileField(blank=True, default='', null=True, upload_to='', verbose_name='Фоновое изображение')),
                ('item', models.ManyToManyField(blank=True, to='indexpage.Item', verbose_name='Элемент (списка, картинка)')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
    ]
