# Generated by Django 2.2.12 on 2022-06-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0002_auto_20220608_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='footer',
            field=models.TextField(blank=True, default='<p>© Разработка сайта. Есина М.В., 2022 <a href="https://diceshard.ru" target="_blank">diceshard.ru</a></p>', null=True, verbose_name='Текст футера, копирайт'),
        ),
        migrations.AddField(
            model_name='settings',
            name='map',
            field=models.TextField(blank=True, default='<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A113fbee5d8cac314649ce7156155a694d81b21bea2dc918f36e1f484c6eb3d54&amp;width=100%25&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>', null=True, verbose_name='Код карты'),
        ),
    ]
