# Generated by Django 2.2.12 on 2022-06-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0003_auto_20220609_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(default='', max_length=128, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='requisites',
            field=models.TextField(blank=True, default='Местная религиозная организация Церковь Христиан Веры Евангельской (пятидесятников) «Благословение» г. Барнаул, Алтайский край \nОГРН: 1112202000800 ИНН: 2223995025 КПП: 222501001', null=True, verbose_name='Реквизиты'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Заголовок вкладки'),
        ),
    ]
